FROM rocm/dev-ubuntu-24.04
WORKDIR /crast

RUN apt update && apt install -y \
    wget \
    cmake \
    git

RUN apt install -y \
    libglfw3-dev \
    libboost-all-dev \
    rocprim-dev \
    rocthrust-dev \
    hipcub-dev

COPY CMakeLists.txt ./
COPY src src
COPY external external
